# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


jobs:
  say-hello:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Build docker image
          command: docker build -t sunilshegu/test-image .
      - run:
          name: Docker login
          command: docker login -u="sunilshegu" -p="9f60131b-705c-406c-a1a9-75ea4f74241c"
      - run:
          name: Push to docker hub
          command: docker push sunilshegu/test-image

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
